#!/usr/bin/env python3
"""Generate the terminal code themes from one set of palettes.

Writes the editor highlighter palettes (FSNotesCore/SwiftHighlighter/Themes/TerminalThemes.swift)
and the matching preview stylesheets (Resources/MPreview.bundle/styles/<theme>-<variant>.min.css),
so a theme looks the same in the editor and in the preview.

Run from anywhere: python3 scripts/generate-code-themes.py
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SWIFT = ROOT / "FSNotesCore/SwiftHighlighter/Themes/TerminalThemes.swift"
STYLES = ROOT / "Resources/MPreview.bundle/styles"

FIELDS = ["text", "background", "comment", "keyword", "string", "number",
          "title", "type", "literal", "tag", "strong"]

# name -> {variant: palette}. Themes with only a dark variant use it in light mode too.
# Colour values are each project's published palette (all MIT licensed; see Licenses/BASE_NOTICES.md).
# Any colour below 4.5:1 against its background is moved toward white (dark themes) or black
# (light themes) until it reaches 4.5:1, so code stays readable; see readable().
THEMES = {
    "consolinotes": {
        "description": "the consolinotes Vim modal palette",
        "dark": dict(text="#dcd3c0", background="#232220", comment="#a69d8b", keyword="#c9a0d6",
                     string="#a9c26f", number="#e8a063", title="#83a9cc", type="#e3b341",
                     literal="#7fc7b2", tag="#ee8e7c", strong="#f4ecd8"),
        "light": dict(text="#3a352d", background="#f0eadd", comment="#5b5447", keyword="#7d4893",
                      string="#3f580b", number="#8a440a", title="#2b5d88", type="#725000",
                      literal="#1c6b59", tag="#9a3020", strong="#1c1914"),
    },
    "gruvbox": {
        "description": "Gruvbox by Pavel Pertsev",
        "dark": dict(text="#ebdbb2", background="#282828", comment="#928374", keyword="#fb4934",
                     string="#b8bb26", number="#d3869b", title="#8ec07c", type="#fabd2f",
                     literal="#d3869b", tag="#fe8019", strong="#fbf1c7"),
        "light": dict(text="#3c3836", background="#fbf1c7", comment="#7c6f64", keyword="#9d0006",
                      string="#79740e", number="#8f3f71", title="#427b58", type="#b57614",
                      literal="#8f3f71", tag="#af3a03", strong="#282828"),
    },
    "tokyo-night": {
        "description": "Tokyo Night (night and day) by enkia",
        "dark": dict(text="#c0caf5", background="#1a1b26", comment="#565f89", keyword="#bb9af7",
                     string="#9ece6a", number="#ff9e64", title="#7aa2f7", type="#2ac3de",
                     literal="#73daca", tag="#f7768e", strong="#c0caf5"),
        "light": dict(text="#3760bf", background="#e1e2e7", comment="#848cb5", keyword="#9854f1",
                      string="#587539", number="#b15c00", title="#2e7de9", type="#007197",
                      literal="#387068", tag="#f52a65", strong="#3760bf"),
    },
    "catppuccin": {
        "description": "Catppuccin (Mocha and Latte)",
        "dark": dict(text="#cdd6f4", background="#1e1e2e", comment="#9399b2", keyword="#cba6f7",
                     string="#a6e3a1", number="#fab387", title="#89b4fa", type="#f9e2af",
                     literal="#94e2d5", tag="#f38ba8", strong="#cdd6f4"),
        "light": dict(text="#4c4f69", background="#eff1f5", comment="#7c7f93", keyword="#8839ef",
                      string="#40a02b", number="#fe640b", title="#1e66f5", type="#df8e1d",
                      literal="#179299", tag="#d20f39", strong="#4c4f69"),
    },
    "nord": {
        "description": "Nord by Arctic Ice Studio",
        "dark": dict(text="#d8dee9", background="#2e3440", comment="#616e88", keyword="#81a1c1",
                     string="#a3be8c", number="#b48ead", title="#88c0d0", type="#8fbcbb",
                     literal="#81a1c1", tag="#bf616a", strong="#eceff4"),
    },
    "dracula": {
        "description": "Dracula",
        "dark": dict(text="#f8f8f2", background="#282a36", comment="#6272a4", keyword="#ff79c6",
                     string="#f1fa8c", number="#bd93f9", title="#50fa7b", type="#8be9fd",
                     literal="#bd93f9", tag="#ff5555", strong="#f8f8f2"),
    },
}

CSS = """pre code.hljs {{
  display: block;
  overflow-x: auto;
  padding: 1em
}}
code.hljs {{
  padding: 3px 5px
}}
/*

{name} {variant}: {description}.
Generated by scripts/generate-code-themes.py with FSNotesCore/SwiftHighlighter/Themes/TerminalThemes.swift.

*/
.hljs {{
  color: {text};
  background: {background}
}}
.hljs-comment,
.hljs-quote {{
  color: {comment};
  font-style: italic
}}
.hljs-doctag,
.hljs-keyword,
.hljs-formula {{
  color: {keyword}
}}
.hljs-name,
.hljs-selector-tag,
.hljs-deletion,
.hljs-subst {{
  color: {tag}
}}
.hljs-literal {{
  color: {literal}
}}
.hljs-string,
.hljs-regexp,
.hljs-addition,
.hljs-attribute,
.hljs-meta .hljs-string {{
  color: {string}
}}
.hljs-attr,
.hljs-variable,
.hljs-template-variable,
.hljs-selector-class,
.hljs-selector-attr,
.hljs-selector-pseudo,
.hljs-number {{
  color: {number}
}}
.hljs-symbol,
.hljs-bullet,
.hljs-link,
.hljs-meta,
.hljs-section,
.hljs-selector-id,
.hljs-title {{
  color: {title}
}}
.hljs-type,
.hljs-built_in,
.hljs-title.class_,
.hljs-class .hljs-title {{
  color: {type}
}}
.hljs-emphasis {{
  font-style: italic
}}
.hljs-strong {{
  color: {strong};
  font-weight: bold
}}
.hljs-link {{
  text-decoration: underline
}}
"""

SWIFT_HEADER = """//
//  TerminalThemes.swift
//  FSNotes
//
//  Code highlighting palettes for the terminal themes. Generated by scripts/generate-code-themes.py,
//  which also writes the matching MPreview.bundle/styles/*.min.css. Edit the palettes there.
//

struct CodePalette {
    let text, background, comment, keyword, string, number, title, type, literal, tag, strong: String

    func style() -> HighlightStyle {
        var style = HighlightStyle()

        style.font = UserDefaultsManagement.codeFont
        style.foregroundColor = PlatformColor(hex: text)
        style.backgroundColor = PlatformColor(hex: background)

        func set(_ names: [String], _ hex: String, _ traits: FontTraits = []) {
            for name in names {
                style.styles[name] = .init(color: PlatformColor(hex: hex), traits: traits)
            }
        }

        set(["comment", "quote"], comment, [.italic])
        set(["keyword", "formula", "doctag"], keyword)
        set(["string", "regexp", "addition", "attribute"], string)
        set(["number", "attr", "variable", "template-variable"], number)
        set(["title", "symbol", "bullet", "link", "meta", "id", "section"], title)
        set(["type", "built_in", "class"], type)
        set(["literal"], literal)
        set(["name", "tag", "deletion", "subst"], tag)
        set(["emphasis"], text, [.italic])
        set(["strong"], strong, [.bold])

        return style
    }
}

enum TerminalThemes {
"""


def luminance(hex_colour):
    channels = [int(hex_colour[i:i + 2], 16) / 255 for i in (1, 3, 5)]
    linear = [c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4 for c in channels]
    return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2]


def contrast(a, b):
    la, lb = luminance(a), luminance(b)
    return (max(la, lb) + 0.05) / (min(la, lb) + 0.05)


def readable(colour, background, target=4.5):
    """Mix a colour toward white or black, away from the background, until it reaches the target contrast."""
    toward = 255 if luminance(background) < 0.5 else 0
    original = [int(colour[i:i + 2], 16) for i in (1, 3, 5)]
    rgb = original
    step = 0
    while contrast("#%02x%02x%02x" % tuple(rgb), background) < target and step < 100:
        step += 1
        rgb = [round(c + (toward - c) * step / 100) for c in original]
    return "#%02x%02x%02x" % tuple(rgb)


def identifier(name, variant):
    parts = name.split("-") + [variant]
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def main():
    swift = [SWIFT_HEADER]
    written = []

    for name, theme in THEMES.items():
        swift.append(f"    // {theme['description']}\n")
        for variant in ("dark", "light"):
            palette = theme.get(variant)
            if palette is None:
                continue
            assert set(palette) == set(FIELDS), (name, variant)
            palette = {field: value if field == "background" else readable(value, palette["background"])
                       for field, value in palette.items()}
            args = [f'{field}: "{palette[field]}"' for field in FIELDS]
            lines = [", ".join(args[i:i + 4]) for i in range(0, len(args), 4)]
            body = ",\n        ".join(lines)
            swift.append(f"    static let {identifier(name, variant)} = CodePalette(\n        {body}\n    )\n")

            css = CSS.format(name=name, variant=variant, description=theme["description"], **palette)
            path = STYLES / f"{name}-{variant}.min.css"
            path.write_text(css)
            written.append(path.relative_to(ROOT))
        swift.append("\n")

    swift[-1] = "}\n"
    SWIFT.write_text("".join(swift))
    written.append(SWIFT.relative_to(ROOT))

    for path in written:
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
