//
//  TerminalThemes.swift
//  FSNotes
//
//  Code highlighting palettes for the terminal themes. Generated by scripts/generate-code-themes.py,
//  which also writes the matching MPreview.bundle/styles/*.min.css. Edit the palettes there.
//

struct CodePalette {
    let text, background, comment, keyword, string, number, title, type, literal, tag, strong: String

    func style() -> HighlightStyle {
        var style = HighlightStyle()

        style.font = UserDefaultsManagement.codeFont
        style.foregroundColor = PlatformColor(hex: text)
        style.backgroundColor = PlatformColor(hex: background)

        func set(_ names: [String], _ hex: String, _ traits: FontTraits = []) {
            for name in names {
                style.styles[name] = .init(color: PlatformColor(hex: hex), traits: traits)
            }
        }

        set(["comment", "quote"], comment, [.italic])
        set(["keyword", "formula", "doctag"], keyword)
        set(["string", "regexp", "addition", "attribute"], string)
        set(["number", "attr", "variable", "template-variable"], number)
        set(["title", "symbol", "bullet", "link", "meta", "id", "section"], title)
        set(["type", "built_in", "class"], type)
        set(["literal"], literal)
        set(["name", "tag", "deletion", "subst"], tag)
        set(["emphasis"], text, [.italic])
        set(["strong"], strong, [.bold])

        return style
    }
}

enum TerminalThemes {
    // the consolinotes Vim modal palette
    static let consolinotesDark = CodePalette(
        text: "#dcd3c0", background: "#232220", comment: "#a69d8b", keyword: "#c9a0d6",
        string: "#a9c26f", number: "#e8a063", title: "#83a9cc", type: "#e3b341",
        literal: "#7fc7b2", tag: "#ee8e7c", strong: "#f4ecd8"
    )
    static let consolinotesLight = CodePalette(
        text: "#3a352d", background: "#f0eadd", comment: "#5b5447", keyword: "#7d4893",
        string: "#3f580b", number: "#8a440a", title: "#2b5d88", type: "#725000",
        literal: "#1c6b59", tag: "#9a3020", strong: "#1c1914"
    )

    // Gruvbox by Pavel Pertsev
    static let gruvboxDark = CodePalette(
        text: "#ebdbb2", background: "#282828", comment: "#9a8c7e", keyword: "#fb5440",
        string: "#b8bb26", number: "#d3869b", title: "#8ec07c", type: "#fabd2f",
        literal: "#d3869b", tag: "#fe8019", strong: "#fbf1c7"
    )
    static let gruvboxLight = CodePalette(
        text: "#3c3836", background: "#fbf1c7", comment: "#776b60", keyword: "#9d0006",
        string: "#746f0d", number: "#8f3f71", title: "#417956", type: "#966211",
        literal: "#8f3f71", tag: "#af3a03", strong: "#282828"
    )

    // Tokyo Night (night and day) by enkia
    static let tokyoNightDark = CodePalette(
        text: "#c0caf5", background: "#1a1b26", comment: "#7b82a3", keyword: "#bb9af7",
        string: "#9ece6a", number: "#ff9e64", title: "#7aa2f7", type: "#2ac3de",
        literal: "#73daca", tag: "#f7768e", strong: "#c0caf5"
    )
    static let tokyoNightLight = CodePalette(
        text: "#3760bf", background: "#e1e2e7", comment: "#5e6381", keyword: "#7e46c8",
        string: "#526d35", number: "#9c5100", title: "#2463b8", type: "#006c91",
        literal: "#376e66", tag: "#bf214f", strong: "#3760bf"
    )

    // Catppuccin (Mocha and Latte)
    static let catppuccinDark = CodePalette(
        text: "#cdd6f4", background: "#1e1e2e", comment: "#9399b2", keyword: "#cba6f7",
        string: "#a6e3a1", number: "#fab387", title: "#89b4fa", type: "#f9e2af",
        literal: "#94e2d5", tag: "#f38ba8", strong: "#cdd6f4"
    )
    static let catppuccinLight = CodePalette(
        text: "#4c4f69", background: "#eff1f5", comment: "#6b6d7e", keyword: "#8839ef",
        string: "#327d22", number: "#bc4a08", title: "#1d63ee", type: "#986114",
        literal: "#13797f", tag: "#d20f39", strong: "#4c4f69"
    )

    // Nord by Arctic Ice Studio
    static let nordDark = CodePalette(
        text: "#d8dee9", background: "#2e3440", comment: "#949cae", keyword: "#81a1c1",
        string: "#a3be8c", number: "#b690af", title: "#88c0d0", type: "#8fbcbb",
        literal: "#81a1c1", tag: "#cf888f", strong: "#eceff4"
    )

    // Dracula
    static let draculaDark = CodePalette(
        text: "#f8f8f2", background: "#282a36", comment: "#8390b7", keyword: "#ff79c6",
        string: "#f1fa8c", number: "#bd93f9", title: "#50fa7b", type: "#8be9fd",
        literal: "#bd93f9", tag: "#ff5555", strong: "#f8f8f2"
    )
}
